repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    - id: check-json
    - id: check-yaml
    - id: fix-encoding-pragma
    - id: trailing-whitespace
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        types: [file, python]
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      language_version: python3
