name: malbec_socrates
channels:
- conda-forge
dependencies:
- aeolus>=0.4.16
- black
- dask
- flake8
- ipykernel
- ipython
- iris>=3.4
- isort
- matplotlib
- metpy
- mo_pack
- netCDF4
- numpy
- pandas
- pre-commit
- python>=3.11
- pip
- pytest
- tqdm
- xarray
- pip:
  - git+https://github.com/metomi/mule.git#egg=mule&subdirectory=mule
